In [1]:
import pandas as pd
import numpy as np
import re
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('emi_prediction_dataset.csv')

C:\Users\abdul\AppData\Local\Temp\ipykernel_9888\24023947.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('emi_prediction_dataset.csv')

In [3]:
df.dtypes

age                        object
gender                     object
marital_status             object
education                  object
monthly_salary             object
employment_type            object
years_of_employment       float64
company_type               object
house_type                 object
monthly_rent              float64
family_size                 int64
dependents                  int64
school_fees               float64
college_fees              float64
travel_expenses           float64
groceries_utilities       float64
other_monthly_expenses    float64
existing_loans             object
current_emi_amount        float64
credit_score              float64
bank_balance               object
emergency_fund            float64
emi_scenario               object
requested_amount          float64
requested_tenure            int64
emi_eligibility            object
max_monthly_emi           float64
dtype: object

In [4]:
df['age'].unique()[:200]

array([38.0, 58.0, 48.0, 32.0, 27.0, 47.0, 37.0, 31.0, 59.0, 49.0, 33.0,
       26.0, 39.0, 57.0, 28.0, '58', '38', '48', '32', '27', '37', '48.0',
       '33', '38.0', '49', '27.0', '31', '39', '47', '59', '32.0', '58.0',
       '57', '26', '28', '58.0.0', '39.0', '26.0', '37.0', '38.0.0',
       '32.0.0'], dtype=object)

In [5]:
df['age'] = df['age'].astype(str).str.extract(r'(\d+)').astype(int)

In [6]:
df['age'].dtype

dtype('int64')

In [7]:
df.isna().sum()

age                          0
gender                       0
marital_status               0
education                 2404
monthly_salary               0
employment_type              0
years_of_employment          0
company_type                 0
house_type                   0
monthly_rent              2426
family_size                  0
dependents                   0
school_fees                  0
college_fees                 0
travel_expenses              0
groceries_utilities          0
other_monthly_expenses       0
existing_loans               0
current_emi_amount           0
credit_score              2420
bank_balance              2426
emergency_fund            2351
emi_scenario                 0
requested_amount             0
requested_tenure             0
emi_eligibility              0
max_monthly_emi              0
dtype: int64

In [8]:
df['gender'].unique()

array(['Female', 'Male', 'female', 'male', 'M', 'MALE', 'F', 'FEMALE'],
      dtype=object)

In [9]:
gender_map = {
    'female' : 'F',
    'Female' : 'F',
    'FEMALE' : 'F',
    'MALE' : 'F',
    'Male' : 'F',
    'male' : 'F',
}

In [10]:
df['gender'] = df['gender'].astype(str).replace(gender_map)

In [11]:
df['marital_status'].unique()

array(['Married', 'Single'], dtype=object)

In [12]:
df['education'].unique()

array(['Professional', 'Graduate', 'High School', 'Post Graduate', nan],
      dtype=object)

In [13]:
df['education'].isna().sum()

np.int64(2404)

In [14]:
df.shape

(404800, 27)

In [15]:
((df['education'].isna().sum()) / df.shape[0]) * 100

np.float64(0.5938735177865613)

In [16]:
df = df.dropna(subset=['education'])

In [17]:
df.shape

(402396, 27)

In [18]:
df.isna().sum()

age                          0
gender                       0
marital_status               0
education                    0
monthly_salary               0
employment_type              0
years_of_employment          0
company_type                 0
house_type                   0
monthly_rent              2417
family_size                  0
dependents                   0
school_fees                  0
college_fees                 0
travel_expenses              0
groceries_utilities          0
other_monthly_expenses       0
existing_loans               0
current_emi_amount           0
credit_score              2405
bank_balance              2411
emergency_fund            2330
emi_scenario                 0
requested_amount             0
requested_tenure             0
emi_eligibility              0
max_monthly_emi              0
dtype: int64

In [19]:
df['monthly_salary'].unique()

array(['82600.0', '21500.0', '86100.0', ..., '56779.0', '56280.0',
       '55905.0'], shape=(13601,), dtype=object)

In [20]:
df['monthly_salary'] = df['monthly_salary'].astype(str).str.extract(r'(\d+)').astype(int)

In [21]:
df['monthly_salary'].unique()

array([82600, 21500, 86100, ..., 56779, 56280, 55905], shape=(12762,))

In [22]:
df['monthly_salary'].dtype

dtype('int64')

In [23]:
df['employment_type'].unique()

array(['Private', 'Government', 'Self-employed'], dtype=object)

In [24]:
df['employment_type'].isna().sum()

np.int64(0)

In [25]:
df['years_of_employment'].unique()[:30]

array([ 0.9,  7. ,  5.8,  2.2,  3.4,  5. , 36. , 12.9,  1.9,  7.5,  3.7,
        1.3,  3.2,  0.5, 26. ,  0.8,  4.2,  2.6,  3.9,  9.7,  4.7,  9.6,
        1.7,  9.4,  4.1,  1. ,  7.6, 16. ,  2.5,  1.6])

In [26]:
df['years_of_employment'].dtype

dtype('float64')

In [27]:
df['company_type'].isna().sum()

np.int64(0)

In [28]:
df['company_type'].dtype

dtype('O')

In [29]:
df['company_type'].unique()

array(['Mid-size', 'MNC', 'Startup', 'Large Indian', 'Small'],
      dtype=object)

In [30]:
df['house_type'].unique()

array(['Rented', 'Family', 'Own'], dtype=object)

In [31]:
df['house_type'].isna().sum()

np.int64(0)

In [32]:
df['monthly_rent'].unique()[:40]

array([20000.,     0., 13500., 13100., 11700., 17600.,  8400., 16400.,
        3800.,  7200., 14400.,  6700., 28300., 10900., 18300., 16900.,
       18000., 10200.,  9500., 29500., 16224., 27800.,  5700., 11500.,
       13900.,  9600., 11300., 16500., 13700., 13000., 12700., 12800.,
       24900., 36500., 18200., 21800., 10400., 18500., 17900., 11900.])

In [33]:
df['monthly_rent'].isna().sum()

np.int64(2417)

In [34]:
df['monthly_rent'].dtype

dtype('float64')

In [35]:
df = df.dropna(subset=['monthly_rent'])

In [36]:
df['monthly_rent'].isna().sum()

np.int64(0)

In [37]:
df.shape

(399979, 27)

In [38]:
df['family_size'].isna().sum()

np.int64(0)

In [39]:
df['family_size'].unique()

array([3, 2, 4, 5, 1])

In [40]:
df['dependents'].unique()

array([2, 1, 3, 4, 0])

In [41]:
df['school_fees'].unique()

array([    0.,  5100., 11400.,  9400., 10200., 15000.,  8100., 10900.,
       12000.,  9100., 10800.,  9300., 11700.,  5500.,  5400.,  8000.,
        2400., 14400.,  3000., 12900.,  8300., 10600., 12300., 13800.,
        9900., 12500.,  5900.,  3900.,  8500., 12700.,  6800.,  7900.,
       11000.,  7700., 14100., 14300., 11200.,  4700., 11600.,  6500.,
        6200., 10300.,  9800.,  5700.,  5200.,  2500.,  2000., 14500.,
        9500.,  5000.,  8800., 11800.,  5300.,  2700.,  9600.,  7300.,
        8200., 11300.,  4200.,  2200.,  3400.,  2100., 14700., 13500.,
        8600., 10500.,  4400.,  3200., 10700.,  9000.,  5600.,  3500.,
        7600., 13100.,  6600., 12800., 11100.,  3600., 13900.,  4500.,
        7500.,  7400.,  2900., 11900.,  4100.,  8700.,  3800., 14000.,
       12100.,  5800., 10000.,  7100., 10100.,  3700.,  7000., 14900.,
        3300.,  4300.,  4600., 14200.,  6300.,  2300.,  6100., 13000.,
       13200., 11500.,  8900., 13400.,  2600., 13600., 14600.,  8400.,
        9200., 12400.,  2800.,  7800.,  6900.,  4900.,  3100., 13300.,
        4000.,  6000., 10400.,  7200., 14800., 12200.,  4800.,  9700.,
        6700., 12600., 13700.,  6400.])

In [42]:
df['school_fees'].isna().sum()

np.int64(0)

In [43]:
df['school_fees'].dtype

dtype('float64')

In [44]:
df.head()

,age,gender,marital_status,education,monthly_salary,employment_type,years_of_employment,company_type,house_type,monthly_rent,...,existing_loans,current_emi_amount,credit_score,bank_balance,emergency_fund,emi_scenario,requested_amount,requested_tenure,emi_eligibility,max_monthly_emi
0,38,F,Married,Professional,82600,Private,0.9,Mid-size,Rented,20000.0,...,Yes,23700.0,660.0,303200.0,70200.0,Personal Loan EMI,850000.0,15,Not_Eligible,500.0
1,38,F,Married,Graduate,21500,Private,7.0,MNC,Family,0.0,...,Yes,4100.0,714.0,92500.0,26900.0,E-commerce Shopping EMI,128000.0,19,Not_Eligible,700.0
2,38,F,Married,Professional,86100,Private,5.8,Startup,Own,0.0,...,No,0.0,650.0,672100.0,324200.0,Education EMI,306000.0,16,Eligible,27775.0
3,58,F,Married,High School,66800,Private,2.2,Mid-size,Own,0.0,...,No,0.0,685.0,440900.0,178100.0,Vehicle EMI,304000.0,83,Eligible,16170.0
4,48,F,Married,Professional,57300,Private,3.4,Mid-size,Family,0.0,...,No,0.0,770.0,97300.0,28200.0,Home Appliances EMI,252000.0,7,Not_Eligible,500.0

In [45]:
df['college_fees'].isna().sum()

np.int64(0)

In [46]:
df['travel_expenses'].isna().sum()

np.int64(0)

In [47]:
df['groceries_utilities'].isna().sum()

np.int64(0)

In [48]:
df['other_monthly_expenses'].isna().sum()

np.int64(0)

In [49]:
df['existing_loans'].isna().sum()

np.int64(0)

In [50]:
df['existing_loans'].unique()

array(['Yes', 'No'], dtype=object)

In [51]:
df['current_emi_amount'].isna().sum()

np.int64(0)

In [52]:
df['credit_score'].isna().sum()

np.int64(2389)

In [53]:
df['credit_score'].unique()

array([ 660.,  714.,  650.,  685.,  770.,  792.,  741.,  623.,  712.,
        681.,  791.,  560.,  695.,  691.,  788.,  664.,  662.,  665.,
        655.,  719.,  663.,  765.,  804.,  755.,  808.,  710.,  769.,
        648.,  746.,  614.,  819.,  570.,  606.,  717.,  546.,  702.,
        718.,  694.,  729.,  732.,  705.,  850.,  697.,  737.,  670.,
        700.,  727.,  628.,  731.,  730.,  745.,  798.,  668.,  653.,
        735.,  630.,  704.,  686.,  716.,  678.,  578.,  762.,  693.,
        756.,  703.,  799.,  543.,  690.,  639.,  669.,  608.,  728.,
        676.,  777.,  636.,  840.,  616.,  849.,  688.,  722.,  725.,
        617.,  739.,  637.,  706.,  846.,  818.,  654.,  698.,  631.,
        753.,  790.,  713.,  738.,  696.,  821.,  626.,  618.,  658.,
        841.,  679.,  794.,  646.,  780.,  640.,  721.,  692.,  673.,
        656.,  843.,  715.,  701.,  754.,  805.,  595.,  576.,  747.,
         nan,  644.,  776.,  734.,  751., 1200.,  682.,  625.,  720.,
        811.,  523.,  778.,  652.,  708.,  736.,  675.,  588.,  647.,
        531.,  752.,  633.,  645.,  748.,  772.,  766.,  711.,  683.,
        768.,  689.,  600.,  744.,  699.,  659.,  707.,  598.,  620.,
        643.,  611.,  651.,    0.,  574.,  587.,  677.,  838.,  733.,
        759.,  627.,  742.,  750.,  774.,  657.,  999.,  607.,  767.,
        642.,  540.,  680.,  764.,  785.,  723.,  621.,  589.,  672.,
        815.,  586.,  674.,  624.,  797.,  740.,  568.,  795.,  763.,
        666.,  612.,  615.,  758.,  634.,  641.,  518.,  743.,  782.,
        823.,  775.,  757.,  783.,  609.,  661.,  803.,  801.,  687.,
        671.,  550.,  584.,  596.,  559.,  787.,  569.,  684.,  454.,
        580.,  806.,  749.,  807.,  812.,  831.,  836.,  771.,  592.,
        619.,  827.,  824.,  610.,  597.,  582.,  726.,  709.,  761.,
        603.,  724.,  789.,  796.,  632.,  622.,  581.,  800.,  565.,
        667.,  835.,  810.,  813.,  779.,  828.,  635.,  495.,  466.,
        555.,  585.,  649.,  556.,  760.,  825.,  604.,  548.,  527.,
        602.,  773.,  583.,  594.,  793.,  784.,  809.,  847.,  573.,
        599.,  493.,  566.,  593.,  833.,  601.,  844.,  579.,  557.,
        826.,  814.,  535.,  590.,  613.,  781.,  638.,  505.,  802.,
        629.,  605.,  564.,  834.,  817.,  562.,  832.,  820.,  547.,
        845.,  786.,  591.,  848.,  538.,  552.,  534.,  830.,  577.,
        822.,  532.,  551.,  553.,  571.,  575.,  837.,  816.,  533.,
        839.,  558.,  497.,  526.,  510.,  563.,  521.,  561.,  572.,
        471.,  567.,  494.,  507.,  506.,  842.,  541.,  536.,  528.,
        544.,  549.,  472.,  482.,  829.,  512.,  539.,  554.,  520.,
        503.,  514.,  542.,  537.,  469.,  519.,  502.,  515.,  516.,
        530.,  524.,  529.,  509.,  545.,  504.,  501.,  467.,  452.,
        511.,  481.,  484.,  474.,  486.,  522.,  513.,  498.,  488.,
        479.,  517.,  525.,  485.,  496.,  492.,  429.,  450.,  490.,
        464.,  508.,  483.,  500.,  489.,  462.,  478.,  499.,  491.,
        427.,  442.,  447.,  465.,  449.,  463.,  433.,  441.,  460.,
        487.,  468.,  439.,  448.,  477.,  436.,  461.,  475.,  440.,
        456.,  457.,  470.,  476.,  480.,  453.,  473.,  409.,  430.,
        410.,  451.,  425.,  432.,  459.,  424.,  446.,  407.,  434.,
        458.,  417.,  443.,  421.,  431.])

In [54]:
df = df.dropna(subset=['credit_score'])

In [55]:
df['credit_score'].isna().sum()

np.int64(0)

In [56]:
df['credit_score'].isna().sum()

np.int64(0)

In [57]:
df['emergency_fund'].isna().sum()

np.int64(2300)

In [58]:
df['bank_balance'] = pd.to_numeric(df['bank_balance'], errors='coerce')

In [59]:
df = df.dropna(subset=['bank_balance','emergency_fund'])

In [60]:
df.shape

(391003, 27)

In [61]:
df['emi_scenario'].unique()

array(['Personal Loan EMI', 'E-commerce Shopping EMI', 'Education EMI',
       'Vehicle EMI', 'Home Appliances EMI'], dtype=object)

In [62]:
df['requested_amount'].dtype

dtype('float64')

In [63]:
df['requested_tenure'].dtype

dtype('int64')

In [ ]:
df['emi_eligibility'].isna().sum()

np.int64(0)

In [65]:
df['max_monthly_emi'].isna().sum()

np.int64(0)

In [66]:
df.describe()

,age,monthly_salary,years_of_employment,monthly_rent,family_size,dependents,school_fees,college_fees,travel_expenses,groceries_utilities,other_monthly_expenses,current_emi_amount,credit_score,bank_balance,emergency_fund,requested_amount,requested_tenure,max_monthly_emi
count,391003.000000,391003.000000,391003.000000,391003.000000,391003.000000,391003.000000,391003.000000,391003.000000,391003.000000,391003.000000,391003.000000,391003.000000,391003.000000,3.910030e+05,391003.000000,3.910030e+05,391003.000000,391003.000000
mean,38.877239,59497.469055,5.368918,5825.720064,2.940553,1.940553,4626.056578,4067.813546,5686.282202,12804.660067,7119.248957,4540.832168,700.854561,2.416819e+05,96756.310821,3.709495e+05,29.125178,6764.863156
std,9.300143,43359.602974,6.083775,8644.316643,1.075053,1.075053,5061.314027,7320.774393,3392.210023,6992.795163,4510.267168,7033.211370,88.460340,1.832143e+05,81343.909626,3.452209e+05,18.097308,7746.874070
min,26.000000,3967.000000,0.500000,0.000000,1.000000,0.000000,0.000000,0.000000,600.000000,1800.000000,600.000000,0.000000,0.000000,6.100000e+03,1400.000000,1.000000e+04,3.000000,500.000000
25%,32.000000,35400.000000,1.200000,0.000000,2.000000,1.000000,0.000000,0.000000,3200.000000,7700.000000,3800.000000,0.000000,654.000000,1.044000e+05,38400.000000,1.240000e+05,15.000000,500.000000
50%,38.000000,51635.000000,3.200000,0.000000,3.000000,2.000000,3100.000000,0.000000,4900.000000,11400.000000,6000.000000,0.000000,701.000000,1.959000e+05,74000.000000,2.370000e+05,25.000000,4211.200000
75%,48.000000,73000.000000,7.200000,10600.000000,4.000000,3.000000,9000.000000,6500.000000,7400.000000,16400.000000,9300.000000,8000.000000,748.000000,3.312500e+05,130600.000000,4.945000e+05,40.000000,9792.000000
max,59.000000,499970.000000,36.000000,80000.000000,5.000000,4.000000,15000.000000,25000.000000,30300.000000,71200.000000,42900.000000,56300.000000,1200.000000,1.717300e+06,891500.000000,1.500000e+06,84.000000,91040.400000

In [67]:
df.to_csv("cleaned_emi_prediction_dataset.csv", index=False)

In [69]:
df_cleaned = pd.read_csv("cleaned_emi_prediction_dataset.csv")

In [70]:
df_cleaned.dtypes

age                         int64
gender                     object
marital_status             object
education                  object
monthly_salary              int64
employment_type            object
years_of_employment       float64
company_type               object
house_type                 object
monthly_rent              float64
family_size                 int64
dependents                  int64
school_fees               float64
college_fees              float64
travel_expenses           float64
groceries_utilities       float64
other_monthly_expenses    float64
existing_loans             object
current_emi_amount        float64
credit_score              float64
bank_balance              float64
emergency_fund            float64
emi_scenario               object
requested_amount          float64
requested_tenure            int64
emi_eligibility            object
max_monthly_emi           float64
dtype: object